-- Phase 2F: pooja_bookings (MongoDB → PostgreSQL migration).
-- Mirrors backend/src/models/PoojaBooking.js and its real usages in the
-- application (poojaBookingController create/getMyBookings/cancel, the app.js
-- daily cron that looks up upcoming poojas by bookingDate, poojaBookingRoutes).
-- Primary keys are 24-char hex strings so they remain compatible with existing
-- MongoDB ObjectIds: Bill.sourceId points at pooja bookings (billType
-- 'Pooja Booking'), AccountTransaction.referenceId points at them with
-- referenceModel = 'PoojaBooking', and the Mongo PoojaBooking._id is returned
-- to the cashier frontend. Monetary values use NUMERIC so pooja booking
-- amounts round-trip exactly.
--
-- Date/time semantics preserved from the Mongo model:
--   * bookingDate — Mongoose Date (an instant). The controller parses it as a
--     Date (new Date(bookingDate)) and the app.js daily cron compares it
--     against midnight TIMESTAMPTZ boundaries (bookingDate: { $gte: tomorrow,
--     $lt: dayAfterTomorrow }), so it maps to TIMESTAMPTZ.
--   * createdAt / updatedAt — the Mongo schema declares timestamps: true, so
--     they are real instants → TIMESTAMPTZ NOT NULL DEFAULT now().
--
-- Enums (from the Mongo schema, preserved exactly — no extra values):
--   * paymentMethod: ['UPI', 'Cash', 'Card'] — required.
--   * status: ['Booked', 'Completed', 'Cancelled'] — default 'Booked'.
--   * materialStatus: ['N/A', 'Pending', 'Approved', 'Reserved', 'Ready',
--     'Issued', 'Consumed', 'Cancelled'] — default 'N/A'.
--
-- Embedded/nested data:
--   * templeMaterialRequests[] → pooja_booking_material_requests child table.
--     The create path (poojaBookingController.createBooking) writes entries with
--     item/itemName/qty/unit, and the cashier pages read them back keyed by the
--     booking. Array order matters and is preserved with a position column.
--   * priestChecklist → JSONB. A flat map of six boolean flags; always
--     read/written as a whole and never queried by inner field — the same
--     decision made for bookings.priest_checklist in Phase 2E.
--
-- References (createdBy → Employee) stay plain indexed TEXT holding Mongo
-- ObjectId values. The employees table exists in PostgreSQL (Phase 2A) but
-- MongoDB remains the source of truth for it, so no FK is created — consistent
-- with the Phase 2A/2B/2C/2D/2E convention. bills.source_id stays polymorphic
-- TEXT (it also references bookings, donations and prasadam orders), and
-- account_transactions.reference_id stays polymorphic TEXT, so no FKs are
-- created to either table from pooja_bookings either.
--
-- bookingNumber is unique in Mongo (unique: true) and auto-generated by a
-- pre-validate hook (PB1001 onwards). The UNIQUE constraint preserves the
-- uniqueness; the repository mirrors the generation algorithm for rows created
-- through it. There is no foreign-key relationship between pooja_bookings and
-- bookings: the Mongo PoojaBooking model contains no bookingId/reference to
-- the bookings table, so none is created here.

CREATE TABLE IF NOT EXISTS pooja_bookings (
  id TEXT PRIMARY KEY,
  booking_number TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  service TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  payment_method TEXT NOT NULL,
  contact_number TEXT NOT NULL,
  email TEXT,
  address TEXT,
  notes TEXT NOT NULL DEFAULT '',
  -- Mongoose Date (instant); the app.js cron filters by midnight range.
  booking_date TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'Booked',
  -- createdBy is a Mongo ObjectId ref to Employee; kept as plain indexed TEXT
  -- (employees is still Mongo-backed as the source of truth).
  created_by TEXT NOT NULL,
  temple_arrangement BOOLEAN NOT NULL DEFAULT FALSE,
  temple_material_charge NUMERIC NOT NULL DEFAULT 0,
  material_status TEXT NOT NULL DEFAULT 'N/A',
  -- Flat map of six boolean flags in Mongo; stored as JSONB and kept as an
  -- object (the Mongo sub-document is always an object).
  priest_checklist JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pooja_bookings_payment_method_check CHECK (payment_method IN ('UPI', 'Cash', 'Card')),
  CONSTRAINT pooja_bookings_status_check CHECK (status IN ('Booked', 'Completed', 'Cancelled')),
  CONSTRAINT pooja_bookings_material_status_check CHECK (material_status IN ('N/A', 'Pending', 'Approved', 'Reserved', 'Ready', 'Issued', 'Consumed', 'Cancelled')),
  -- The Mongo model declares amount: { required: true } with no min; every real
  -- write path (poojaBookingController.createBooking) rejects a falsy amount,
  -- so a non-negative CHECK preserves the actual application semantics.
  CONSTRAINT pooja_bookings_amount_check CHECK (amount >= 0),
  CONSTRAINT pooja_bookings_temple_material_charge_check CHECK (temple_material_charge >= 0),
  -- Mirrors the Mongo schema's unique: true on bookingNumber.
  CONSTRAINT pooja_bookings_booking_number_key UNIQUE (booking_number),
  CONSTRAINT pooja_bookings_priest_checklist_object_check CHECK (jsonb_typeof(priest_checklist) = 'object')
);

CREATE TABLE IF NOT EXISTS pooja_booking_material_requests (
  id TEXT PRIMARY KEY,
  pooja_booking_id TEXT NOT NULL,
  -- Preserves the original array order of the Mongo
  -- PoojaBooking.templeMaterialRequests[] embedded array.
  position INTEGER NOT NULL DEFAULT 0,
  item TEXT,
  item_name TEXT,
  qty TEXT,
  unit TEXT,
  FOREIGN KEY (pooja_booking_id) REFERENCES pooja_bookings(id) ON DELETE CASCADE
);

-- getMyBookings sorts by createdAt DESC and filters by createdBy (the logged-in
-- cashier/admin), with an optional status filter and a customerName/service/
-- bookingNumber search.
CREATE INDEX IF NOT EXISTS idx_pooja_bookings_created_at ON pooja_bookings (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pooja_bookings_created_by ON pooja_bookings (created_by);
-- app.js daily cron: PoojaBooking.find({ status: 'Booked', bookingDate:
-- { $gte: tomorrow, $lt: dayAfterTomorrow } }).
CREATE INDEX IF NOT EXISTS idx_pooja_bookings_booking_date ON pooja_bookings (booking_date);
CREATE INDEX IF NOT EXISTS idx_pooja_bookings_status ON pooja_bookings (status);
-- Support the anonymous service-text lookups and admin cancel/delete flows.
CREATE INDEX IF NOT EXISTS idx_pooja_bookings_service ON pooja_bookings (service);
-- The child rows are read back with the booking and written in order; the child
-- FK is covered by the composite ordering index.
CREATE INDEX IF NOT EXISTS idx_pooja_booking_material_requests_pooja_booking_id_position
  ON pooja_booking_material_requests (pooja_booking_id, position);